In [1]:
!pip install kaggle

Collecting kaggle
  Downloading kaggle-1.7.4.5-py3-none-any.whl.metadata (16 kB)
Collecting bleach (from kaggle)
  Downloading bleach-6.2.0-py3-none-any.whl.metadata (30 kB)
Collecting certifi>=14.05.14 (from kaggle)
  Downloading certifi-2025.8.3-py3-none-any.whl.metadata (2.4 kB)
Collecting charset-normalizer (from kaggle)
  Downloading charset_normalizer-3.4.3-cp310-cp310-win_amd64.whl.metadata (37 kB)
Collecting idna (from kaggle)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting protobuf (from kaggle)
  Downloading protobuf-6.32.0-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\namee\onedrive\desktop\mlops\venvironment\lib\site-packages (from kaggle) (2.9.0.post0)
Collecting python-slugify (from kaggle)
  Downloading python_slugify-8.0.4-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting requests (from kaggle)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\namee\onedrive\desktop\mlops\venvironment\lib\site-packages (from kaggle) (78.1.1)
Requirement already satisfied: six>=1.10 in c:\users\namee\onedrive\desktop\mlops\venvironment\lib\site-packages (from kaggle) (1.17.0)
Collecting text-unidecode (from kaggle)
  Downloading text_unidecode-1.3-py2.py3-none-any.whl.metadata (2.4 kB)
Collecting tqdm (from kaggle)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting urllib3>=1.15.1 (from kaggle)
  Downloading urllib3-2.5.0-py3-none-any.whl.metadata (6.5 kB)
Collecting webencodings (from kaggle)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: colorama in c:\users\namee\onedrive\desktop\mlops\venvironment\lib\site-packages (from tqdm->kaggle) (0.4.6)
Downloading kaggle-1.7.4.5-py3-none-any.whl (181 kB)
Downloading certifi-2025.8.3-py3-none-any.whl (161 kB)
Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
Downloading bleach-6.2.0-py3-none-any.whl (163 kB)
Downloading charset_normalizer-3.4.3-cp310-cp310-win_amd64.whl (107 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Downloading protobuf-6.32.0-cp310-abi3-win_amd64.whl (435 kB)
Downloading python_slugify-8.0.4-py2.py3-none-any.whl (10 kB)
Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, text-unidecode, urllib3, tqdm, python-slugify, protobuf, idna, charset-normalizer, certifi, bleach, requests, kaggle

   ----------------------------------------  0/12 [webencodings]
   --- ------------------------------------  1/12 [text-unidecode]
   ------ ---------------------------------  2/12 [urllib3]
   ------ ---------------------------------  2/12 [urllib3]
   ------ ---------------------------------  2/12 [urllib3]
   ------ ---------------------------------  2/12 [urllib3]
   ------ ---------------------------------  2/12 [urllib3]
   ------ ---------------------------------  2/12 [urllib3]
   ------ ---------------------------------  2/12 [urllib3]
   ------ ---------------------------------  2/12 [urllib3]
   ------ ---------------------------------  2/12 [urllib3]
   ---------- -----------------------------  3/12 [tqdm]
   ---------- -----------------------------  3/12 [tqdm]
   ---------- -----------------------------  3/12 [tqdm]
   ---------- -----------------------------  3/12 [tqdm]
   ---------- -----------------------------  3/12 [tqdm]
   ---------- -----------------------------  3/12 [tqdm]
   ---------- -----------------------------  3/12 [tqdm]
   ---------- -----------------------------  3/12 [tqdm]
   ------------- --------------------------  4/12 [python-slugify]
   ------------- --------------------------  4/12 [python-slugify]
   ------------- --------------------------  4/12 [python-slugify]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   -------------------- -------------------  6/12 [idna]
   -------------------- -------------------  6/12 [idna]
   -------------------- -------------------  6/12 [idna]
   -------------------- -------------------  6/12 [idna]
   ----------------------- ----------------  7/12 [charset-normalizer]
   ----------------------- ----------------  7/12 [charset-normalizer]
   ----------------------- ----------------  7/12 [charset-normalizer]
   ----------------------- ----------------  7/12 [charset-normalizer]
   ----------------------- ----------------  7/12 [charset-normalizer]
   -------------------------- -------------  8/12 [certifi]
   ------------------------------ ---------  9/12 [bleach]
   ------------------------------ ---------  9/12 [bleach]
   ------------------------------ ---------  9/12 [bleach]
   ------------------------------ ---------  9/12 [bleach]
   ------------------------------ ---------  9/12 [bleach]
   ------------------------------ ---------  9/12 [bleach]
   ------------------------------ ---------  9/12 [bleach]
   ------------------------------ ---------  9/12 [bleach]
   ------------------------------ ---------  9/12 [bleach]
   ------------------------------ ---------  9/12 [bleach]
   ------------------------------ ---------  9/12 [bleach]
   ------------------------------ ---------  9/12 [bleach]
   ------------------------------ ---------  9/12 [bleach]
   --------------------------------- ------ 10/12 [requests]
   --------------------------------- ------ 10/12 [requests]
   --------------------------------- ------ 10/12 [requests]
   --------------------------------- ------ 10/12 [requests]
   --------------------------------- ------ 10/12 [requests]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ------------------------------------ --- 11/12 [kaggle]
   ---------------------------------------- 12/12 [kaggle]

Successfully installed bleach-6.2.0 certifi-2025.8.3 charset-normalizer-3.4.3 idna-3.10 kaggle-1.7.4.5 protobuf-6.32.0 python-slugify-8.0.4 requests-2.32.5 text-unidecode-1.3 tqdm-4.67.1 urllib3-2.5.0 webencodings-0.5.1

In [2]:
#import
import kaggle
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv to C:\Users\namee\Documents\SQL + Python

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 204MB/s]

In [ ]:
#import zipfile
'''zip_ref = zipfile.ZipFile('orders.csv.zip')
zip_ref.extractall()
zip_ref.close()
'''

In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\namee\onedrive\desktop\mlops\venvironment\lib\site-packages (2.3.0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\namee\onedrive\desktop\mlops\venvironment\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\namee\onedrive\desktop\mlops\venvironment\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\namee\onedrive\desktop\mlops\venvironment\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\namee\onedrive\desktop\mlops\venvironment\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\namee\onedrive\desktop\mlops\venvironment\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
#read dataset
import pandas as pd

df = pd.read_csv(r"D:\CodeBasics Datasets\orders.csv", encoding='ISO-8859-1',na_values=['Not Available', 'unknown'])
df.head()

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [13]:
#preprocessing
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [15]:
# renaming for best practices 
#df.rename(columns={'Order Id':'order_id')
df.columns = df.columns.str.lower()  # converting to small named cols and then removing space
df.columns =  df.columns.str.replace(' ','_')
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [16]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [22]:
#derive new columns
df['discount'] = df['list_price']*df['discount_percent']*0.01
df['sale_price'] = df['list_price']-df['discount']
df['profit'] = df['sale_price']-df['cost_price']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [27]:
df.dtypes #check for date datatype change it to string for operations
df['order_date'] = pd.to_datetime(df['order_date'],format="%Y-%m-%d")
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [29]:
#dropping unneccesary columns
df.drop(columns = ['list_price','discount_percent','cost_price']) #if you want remove rows specify index =...

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [30]:
df #so use inplace = True so remove from the dataset

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [31]:
df.drop(columns = ['list_price','discount_percent','cost_price'],inplace = True)

In [32]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [34]:
!pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.43-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.4-cp310-cp310-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\namee\onedrive\desktop\mlops\venvironment\lib\site-packages (from sqlalchemy) (4.14.0)
Downloading sqlalchemy-2.0.43-cp310-cp310-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 3.3 MB/s eta 0:00:01
   ------------------------ --------------- 1.3/2.1 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 3.7 MB/s eta 0:00:00
Downloading greenlet-3.2.4-cp310-cp310-win_amd64.whl (298 kB)
Installing collected packages: greenlet, sqlalchemy

   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   ---------------------------------------- 2/2 [sqlalchemy]

Successfully installed greenlet-3.2.4 sqlalchemy-2.0.43

In [39]:
!pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.2.0-cp310-cp310-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.2.0-cp310-cp310-win_amd64.whl (68 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.2.0

In [42]:
#connecting to sql
import urllib
import sqlalchemy as sal

# Build params
params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=NAMEETH\\SQLEXPRESS;"
    "DATABASE=master;"
    "Trusted_Connection=yes;"
    "Encrypt=no;"
)

# Create engine with odbc_connect
engine = sal.create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# Test connection
with engine.connect() as conn:
    print("✅ Connection successful")

✅ Connection successful

In [45]:
df.to_sql('df_orders', con=engine, index=False, if_exists='append') #append bcoz data type issues in sql so using append istead of replace

38

In [46]:
'''CREATE TABLE df_orders (
    order_id INT PRIMARY KEY,
    order_date DATE,
    ship_mode VARCHAR(20),
    segment VARCHAR(20),
    country VARCHAR(20),
    city VARCHAR(20),
    state VARCHAR(20),
    postal_code VARCHAR(20),
    region VARCHAR(20),
    category VARCHAR(20),
    sub_category VARCHAR(20),
    product_id VARCHAR(50),
    quantity INT,
    discount DECIMAL(7,2),
    sale_price DECIMAL(7,2),
    profit DECIMAL(7,2)
);'''
#script for sql

'CREATE TABLE df_orders (\n    order_id INT PRIMARY KEY,\n    order_date DATE,\n    ship_mode VARCHAR(20),\n    segment VARCHAR(20),\n    country VARCHAR(20),\n    city VARCHAR(20),\n    state VARCHAR(20),\n    postal_code VARCHAR(20),\n    region VARCHAR(20),\n    category VARCHAR(20),\n    sub_category VARCHAR(20),\n    product_id VARCHAR(50),\n    quantity INT,\n    discount DECIMAL(7,2),\n    sale_price DECIMAL(7,2),\n    profit DECIMAL(7,2)\n);'